function Home() {
  return (
    <section className="flex min-h-[calc(100vh-73px)] w-full flex-col items-center justify-center gap-8 px-6 py-10">
      <h1 className="font-display text-accent text-center text-[10em]">
        FigureS
      </h1>
      <div className="flex max-w-5xl flex-col gap-2">
        <p className="mx-auto max-w-5xl text-center text-lg">
          A simple drawing app customized for figure skaters and coaches.
        </p>
        <p className="mx-auto max-w-5xl text-center text-lg">
          Draw clusters and ice dance patterns, annotate them with text, and
          export them as SVGs to share with others..
        </p>
      </div>

      <footer className="mx-auto flex max-w-xl flex-col gap-4 text-center text-sm">
        <p>
          <span className="font-bold">FigureS</span>: short for Figure Skating,
          inspired by{" "}
          <a
            href="https://en.wikipedia.org/wiki/Compulsory_figures"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent"
          >
            compulsory figures
          </a>
          , and a nod to the possibilities of scientific figures generated by
          this tool.
        </p>
        <p>
          made with ♡ by{" "}
          <a
            href="https://angelazheng.ca"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent"
          >
            Angela Zheng
          </a>
        </p>
      </footer>
    </section>
  );
}

export default Home;
