function Home() {
  return (
    <section className="h-full px-6 py-10 flex flex-col justify-center gap-8">
      <h1 className="font-display text-[10em] text-center">FigureS</h1>
      <div className="flex flex-col gap-2">
        <p className="text-center text-lg max-w-5xl mx-auto">
          A simple drawing app, customized for figure skaters and coaches.
        </p>
        <p className="text-center text-lg max-w-5xl mx-auto">
          Draw clusters and ice dance patterns, annotate them with text, and
          export them as SVGs to share with others..
        </p>
      </div>

      <footer className="text-center text-sm max-w-2xl flex flex-col gap-4 mx-auto">
        <p>
          FigureS: short for Figure Skating, inspired by{" "}
          <a
            href="https://en.wikipedia.org/wiki/Compulsory_figures"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent"
          >
            compulsory figures
          </a>
          , and a nod to the possibilities of scientific figures generated by
          this tool.
        </p>
        <p>
          made with ♡ by{" "}
          <a
            href="https://angelazheng.ca"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent"
          >
            Angela Zheng
          </a>
        </p>
      </footer>
    </section>
  );
}

export default Home;
